[project]
name = "proto_tokenize"
dynamic = ["version"]
authors = [{name="Patrick Elmer", email="patrick@elmer.ws"}]
description = "Convert IPA transcribed words into sequence tokens."
readme = "README.md"

[project.urls]
Home = "https://github.com/PatrickElmer/proto_tokenize"

[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"
