[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tokenize"
authors = [{name = "Patrick Elmer", email = "patrick@elmer.ws"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/PatrickElmer/tokenize"
