[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "proto_tokenize"
authors = [{name = "Patrick Elmer", email = "patrick@elmer.ws"}]
description = "Convert IPA transcribed words into sequence tokens."
dynamic = ["version"]

[project.urls]
Home = "https://github.com/PatrickElmer/tokenize"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "python3 -m pytest ./tests"
